### ISSUE TITLE
User or lib permission issue

### ISSUE THREAD

**Issue by tikismoke** [max5962/essence#1]
As discussed here:
https://github.com/max5962/prixCarburant-home-assistant/issues/2

I got error depending how home assistant is launch (services or directly hass with user in virtualenv).

So i commented try/except in load part (line 140) and got more info:

 ```
2020-05-07 22:37:26 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up prixCarburant platform for sensor
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/prixCarburant/sensor.py", line 57, in setup_platform
    client.load()
  File "/srv/homeassistant/lib/python3.7/site-packages/prixCarburantClient/prixCarburantClient.py", line 145, in load
    "station.csv")
  File "/srv/homeassistant/lib/python3.7/site-packages/prixCarburantClient/prixCarburantClient.py", line 40, in downloadFile
    urllib.request.urlretrieve(url, file)
  File "/usr/lib/python3.7/urllib/request.py", line 257, in urlretrieve
    tfp = open(filename, 'wb')
PermissionError: [Errno 13] Permission denied: 'station.csv'
```

So it appear homeassistant user have limited right to where the lib want to download the file.

**Comment by tikismoke** [comment]
I update my systemd services to add:

```
WorkingDirectory=/home/%i/.homeassistant
```

And all is OK :)

Going to propose a doc update in homeassistant explaining this case.
